apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ausarta-voice

resources:
  - namespace.yaml
  - arq-worker-serviceaccount.yaml
  - configmap-arq-worker.yaml
  - arq-worker-deployment.yaml
  - trigger-authentication-redis.yaml
  - arq-worker-scaledobject.yaml

commonLabels:
  app.kubernetes.io/part-of: ausarta-voice-agent
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/ausarta/voice-agent-backend
    newName: ghcr.io/ausarta/voice-agent-backend
    newTag: latest
